Upgrade workflow to Ubuntu 24.04 and add failure handling
Updated the GitHub Actions workflow to use Ubuntu 24.04 and added a failure handling step for Buildx setup.

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -15,7 +15,7 @@ env:
 jobs:
   build:
     name: Build on Ubuntu
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     steps:
       # https://github.com/jlumbroso/free-disk-space/issues/14
       - name: Update Package List and Remove Dotnet
@@ -91,7 +91,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-    #      ref: bleed
      
       - name : Get date 
         run: |
@@ -101,12 +100,14 @@ jobs:
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v3
+        with:
+          buildkitd-flags: --debug
 
-      #- name: pull old build
-        #run: |
-         #docker pull lsstdesc/desc-cosmology:latest
-         #docker tag lsstdesc/desc-cosmology:latest lsstdesc/desc-cosmology:latest-old
-         #docker push lsstdesc/desc-cosmology:latest-old
+      - name: Run on failure
+        if: failure() && steps.buildx.outcome == 'failure'
+        run: |
+          echo "Buildx setup failed!"
+          exit 1
         
       - name: Build 
         id: docker_build
@@ -126,6 +127,9 @@ jobs:
           docker push lsstdesc/desc-cosmology:latest-${{env.DATE_TAG}}
           docker tag ${{ env.TEST_TAG }} lsstdesc/desc-cosmology:latest
           docker push lsstdesc/desc-cosmology:latest
+          
+          docker tag ${{ env.TEST_TAG }} ghcr.io/lsstdesc/desc-cosmology:latest-${{env.DATE_TAG}}
+          docker push ghcr.io/lsstdesc/desc-cosmology:latest-${{env.DATE_TAG}}
           docker tag ${{ env.TEST_TAG }} ghcr.io/lsstdesc/desc-cosmology:latest
           docker push ghcr.io/lsstdesc/desc-cosmology:latest
        
